---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(here)
```
```{r}
items_df <- read_csv(here("data/20190928-items.csv"))
```
```{r}
names(items_df)
glimpse(items_df)
```
```{r}
#cleaning names which aren't too bad, some column values look messy
items <- clean_names(items_df)

glimpse(items)

```
```{r}
items %>% 
count(brand) %>% 
arrange(desc(n))
```
filter (brand == "Samsung")
```{r}
#filtering for top brand and the continuous variable of rating which needs to be binned for this analysis
top_brand <- items %>% 
  filter (brand == "Samsung")

top_brand %>% 
  ggplot(aes(x = rating)) + 
  geom_histogram(aes(y = ..density..), col = "white", binwidth = .2) +
  stat_function(
    fun = dnorm, #is our data normally distributed?
    args = list(
      mean = mean(top_brand$rating),
      sd = sd(top_brand$rating)
    ),
    col = "red"
  )

#mean(top_brand$rating)
#sd(top_brand$rating)
```
# counting for 3 sigma values (68%,95%,98.7%)
ratings scaled


  
```{r}
#need to select further for single column
samsung_rating <- top_brand %>% 
select(rating)


ratings_scaled <- samsung_rating %>% 
  mutate(z_rating = scale(rating))
```
  
sd1

```{r}
count <-  ratings_scaled%>% 
  filter(between(z_rating, left = -1, right = 1)) %>% 
  nrow()

count/nrow(ratings_scaled)
```

count / nrow(rating_scaled)

sd2

```{r}
count <-  ratings_scaled%>% 
  filter(between(z_rating, left = -2, right = 2)) %>% 
  nrow()

count/nrow(ratings_scaled)
```

sd3
```{r}
count <-  ratings_scaled%>% 
  filter(between(z_rating, left = -3, right = 3)) %>% 
  nrow()

count/nrow(ratings_scaled)
```
SD1 definitely doesn't follow the three sigma rule, and therefore this is not a normal distribution.


