```{r}
#loading libraries
library(here)
library(infer)
library(janitor)
library(tidyverse)
```
```{r}
#loading data
ames <- read_csv(here("data/ames.csv")) %>% 
  clean_names()
```
```{r}
glimpse(ames)
```
task 2

Investigate the distribution of lot_area. Is the distribution roughly normal? If not, what problems do you find?
```{r}
ggplot(ames) +
  aes(x = lot_area) +
  geom_histogram(col = "white", fill = "steel blue", bins  = 40)
```
This is not a normal distribution, skewing right and is also centrally concentrated.


Task 3.
Compute and visualise a bootstrap sampling distribution for the mean(lot_area) of the sold houses.

```{r}
sample_200 <- ames %>% 
  rep_sample_n(size = 200, reps = 1000) %>% 
  summarise(
  mean_lot_area = mean(lot_area)
  )
```

```{r}
#visualizing 

ggplot(sample_200) +
  aes(x = mean_lot_area) +
  geom_histogram(col = "white", fill = "steel blue")

  


```

CI

```{r}
ci_95 <- sample_200 %>% 
  summarise(
    mean = mean(mean_lot_area),
    lower_bound = quantile(mean_lot_area, probs = 0.025),
    upper_bound = quantile(mean_lot_area, probas = 0.975)
  )
```

