```{r}
library(tidyverse)
library(shiny)
library(dplyr)
library(readxl)
library(leaflet)
library(here)
library(janitor)
```

```{r}
#loading data
bird_data <- read_excel(here("raw_data/seabirds.xls"), sheet = "Bird data by record ID")
ship_data <- read_excel(here("raw_data/seabirds.xls"), sheet = "Ship data by record ID")
```

```{r}
# cleaning data 1st run
bird_data_janitor <- clean_names(bird_data)
ship_data_janitor <- clean_names(ship_data)
```

```{r}
# cleaning bird data to make it more readable
bird_data_clean <- bird_data_janitor %>%
 
  rename("species_common" = "species_common_name_taxon_age_sex_plumage_phase",
         "species_scientific" = 
           "species_scientific_name_taxon_age_sex_plumage_phase", 
         "bird_count" = "count") %>% 
   mutate(across(.cols = c(species_common, 
                       species_scientific), 
              .fns = ~str_remove_all(., "[A-Z]{2,5}|PL[0-9]"), 
              .names = NULL)
       ) %>% 
  mutate(abbreviation_clean =  
         str_remove_all(species_abbreviation, 
                        "JUV|AD|IMM|SUB*|DRK|LGHT|PL[0-9]")) %>% 
  select(species_common, species_scientific, abbreviation_clean, bird_count, record_id) 
  write_csv(x = bird_data_clean, 
            file = here("clean_data/bird_data_clean.csv")
            )
            
```

```{r}
#ship data selecting relevant columns for app
ship_data_clean <- ship_data_janitor %>% 
  select(lat, long, record_id, obs, seasn, date)

write_csv(x = ship_data_clean, 
          file = (here("clean_data/ship_data_clean.csv"))
          )
```

#unifiying columns from both sheets to make single df
```{r}
bird_join <- left_join(bird_data_clean, ship_data_clean, by = "record_id")
write_csv(x = bird_join, file = (here("clean_data/bird_join.csv"))
)
```

going to use this in server section to filter for specific birds
filter(str_detect(species_common, input$common_bird_name)) %>% 
drop_na()
